blueprint:
  name: Presence Based Lights
  description: Turn on a light when motion is detected.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            device_class: motion
            domain: binary_sensor
    occupancy_entity:
      name: Occupancy Sensor
      selector:
        entity:
          filter:
            device_class: occupancy
            domain: binary_sensor
    light_target:
      name: Light
      selector:
        entity:
          multiple: true
          domain: light          
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 300
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"
  - trigger: state
    entity_id: !input occupancy_entity
    from: "off"
    to: "on"
  - trigger: state
    entity_id: !input light_target
    from: "off"
    to: "on"

actions:
  - if:
      - condition: state
        entity_id: !input occupancy_entity
        state: "off"
    then:
      - service: light.turn_on
        target: 
          entity_id: !input light_target
      - wait_for_trigger:
          - trigger: state
            entity_id: !input occupancy_entity
            from: "on"
            to: "off"
      - delay: !input no_motion_wait
      - service: light.turn_off
        target: 
          entity_id: !input light_target
    else:
      - if:
        - condition: state
          entity_id: !input occupancy_entity
          state: "off"
        then:
          - delay: !input no_motion_wait
          - service: light.turn_off
            target: 
              entity_id: !input light_target
        else:
          - wait_for_trigger:
              - trigger: state
                entity_id: !input occupancy_entity
                from: "on"
                to: "off"
          - delay: !input no_motion_wait
          - service: light.turn_off
            target: 
              entity_id: !input light_target