blueprint:
  name: Presence Based Lights
  description: Turn on a light when motion is detected.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            device_class: motion
            domain: binary_sensor
    occupancy_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            device_class: occupancy
            domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 5
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: minutes

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"
  - trigger: state
    entity_id: !input occupancy_entity
    from: "off"
    to: "on"

actions:
  - if:
      - condition: state
        entity_id: !input occupancy_entity
        state: "off"
    then:
      - action: light.turn_on
        target: !input light_target
      - wait_for_trigger:
          - trigger: state
            entity_id: !input occupancy_entity
            from: "on"
            to: "off"
      - delay: !input no_motion_wait
      - action: light.turn_off
        target: !input light_target